### ISSUE TITLE
Kitkat support

### ISSUE THREAD

**Issue by mobtechpd** [vijai1996/screenrecorder#10]
Please add android kitkat support with root, many users still use kitkat, very good system

**Comment by vijai1996** [comment]
Thats totally against my motive of providing a no root solution with simple UI and using android native api. Sorry. You request is not happening anytime soon.

**Comment by OffifialMITX** [comment]
> very good system
In Kitkat there are major security issues like missing key pinning.
Marshmallow is not only the design.
