### ISSUE TITLE
Unusable on Cyanogenmod 12.1

### ISSUE THREAD

**Issue by Gyges88** [vijai1996/screenrecorder#12]
I'm using Cyanogenmod 12.1 on a Honor Holly and no matter which settings I choose, I always get a colourful pixel salad, but no actual screen recording.
Might be a codec issue since I was having those with other apps as well.

**Comment by vijai1996** [comment]
As you said yourself that this is the case with other screen recorders also, It is pretty clear its a cyanogen mod bug and it should be reported there.
