### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by krt16s** [vijai1996/screenrecorder#13]
Recent versions started to introduce firebase, which is non-free software. Could you provide a gradle flavor which does not require this?

**Comment by vijai1996** [comment]
That is non intrusive and for receiving crash reports and active installs (analytics). The whole code in opensourced and you can fork the project anytime and build it on your own without firebase. I'd like to reassure that the project will remain opensource and app wont be interested in any of user's data.

**Comment by krt16s** [comment]
For now `sed -i -e '/google-services/d' -e '/firebase/d' build.gradle app/build.gradle` should do it, since I cannot see any firebase specific code. If you intend to add such depending code, I'd really like to see it in a special flavor. Thanks for now.

**Comment by vijai1996** [comment]
It's been on local system for now and is in testing. I do really need to have a number of installs on the app (inclusive of play store and other places) and to get crash reports easily. The reason why firebase is used. If there is any major drawback with that, I'd consider other choices

**Comment by krt16s** [comment]
I'd say countly (https://github.com/Countly/countly-sdk-android) and acra (https://github.com/ACRA) are food options for floss user tracking, but you mileage may vary. As for "other places": f-droid.org cannot build non-free stuff like firebase.

**Comment by vijai1996** [comment]
Thats nice! Never knew those. Might consider them
