### ISSUE TITLE
Floating bar

### ISSUE THREAD

**Issue by OffifialMITX** [vijai1996/screenrecorder#14]
1. It is way too big, at least on devices like mine < 720p.
2. I can't deactivate it, every time I start a recording it switches on by itself.
3. It should be invisible on the recording itself, like the simulated screen (which you activate in the developer settings) is.

This app is still very cool.

**Comment by vijai1996** [comment]
The 2nd one is a known bug and its fixed in local. But we faced a natural disaster recently and I'm out of proper connectivity for over a week. I'd look into the other two when every thing is normal and will push update for the bug as soon as possible

**Comment by OffifialMITX** [comment]
Well, thanks then.
