### ISSUE TITLE
Tracking...?

### ISSUE THREAD

**Issue by OffifialMITX** [vijai1996/screenrecorder#21]
In F-Droid there's a tracking lable on the application and I've noticed that it used the internet connection without any obvious purpose. What kind of data does it send and can there be a possibility to turn that off?

**Comment by vijai1996** [comment]
Yes. There is a FOSS reporting used for crash reporting and anonymous statistics. The data collected 

1. OS version
2. App version
3. The adb log for the crash point
4. Country of usage
5. New user reg vs Old user/returning user

And yeah I found that fdroid requires an option to turn off the analytics and I'll make sure its added in the next release after my dev machine comes back from repairs.

**Comment by vijai1996** [comment]
Everything is back on track again and this is will be the first priority on fix list. Will provide a setting to disable the anonymous analytics

**Comment by OffifialMITX** [comment]
+1

**Comment by vijai1996** [comment]
@OffifialMITX Can you please confirm if the version is released in f-droid? They had issue with theor build server and apps weren't building few weeks back

**Comment by OffifialMITX** [comment]
Yes, V 1.7.2 is released but why don't you check this yourself, if you're not using it you still can go on the official f-droid.org website. (Not like I don't like to help you)
