### ISSUE TITLE
App stops after opening "about" twice

### ISSUE THREAD

**Issue by CBke** [vijai1996/screenrecorder#25]
Open App
Select about 
Go back
Select about 

[https://www.youtube.com/watch?v=moB_sK--ZcU](https://www.youtube.com/watch?v=moB_sK--ZcU)

**Comment by CBke** [comment]
if i build the apk with android studio 2.2.3, i can not reproduce the error.

[app-debug.apk](https://github.com/CBke/screenrecorder/releases/download/49cd398/app-debug.apk)

**Comment by vijai1996** [comment]
@CBke good that the latest repo source has no FC. It is the latest version about to be released. I'm resting it at the moment. Will merge translation and make a release soon. Thanks for testing 

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CBke** [comment]
I'm getting the fault from the build on F-Droid 1.8.1.
Or 49cd398 does not match the [F-Droid apk](https://f-droid.org/repo/com.orpheusdroid.screenrecorder_18.apk).
Or it has something to do with the build options.

Also in 1.8.1 i do not get the option "send error report" like in 17.2 (google play).
I Have Crash Reporting enabled.

**Comment by vijai1996** [comment]
I tried to reproduce the bug on 1.8.1 from f-droid but it works perfect for me. It doesnt FC even if I open about more than twice. Probably some other issue? May be reinstall and try again?

For the "send error report", its not by the app itself but by the Google Play Services. Play services monitor the app installed from play and asks the user to send a error report to the developer's play console if the app crashes. If your source of install is other than play, you wont get that dialog. On the other hand having enabled crash reporting will automatically send the error report in background to the crash analytics platform.

**Comment by vijai1996** [comment]
Closing issue as there is no more update on this
