### ISSUE TITLE
Blank screenshots after recording a video

### ISSUE THREAD

**Issue by Fixallmyproblems** [vijai1996/screenrecorder#26]
So directly after I record all my screenshots are blank and then after some time it isn't, any fix for this?

**Comment by vijai1996** [comment]
I do not completely understand your problem. But If my guess is correct, you're talking about the thumbnail in the videos tab? If yes, it might take sometime to appear as the new video file must be indexed by the android system and thumbnail has to be generated. You can always try to refresh manually with the refresh button if it doesnt work automatically

**Comment by vijai1996** [comment]
Closing as there isn't any update
