### ISSUE TITLE
Doesn't work on my phone (Android 6.0.1 (Marshmallow))

### ISSUE THREAD

**Issue by anonym24** [vijai1996/screenrecorder#27]
my phone: http://www.gsmarena.com/xiaomi_redmi_4_prime-8263.php

Also there is no stop button (notification only shows time and icon of app, no aciton buttons...), activity also has no button, when I press record button it shows toast _screen already recording_

**Comment by vijai1996** [comment]
Hello, I tried on a Xiaomi Redmi note 3 and it works fine on the latest MIUI. The notification has to be expanded with two finger swipe down gesture for the action buttons to show up. Or you could even use the floating controls to stop the recording

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by anonym24** [comment]
seems to be a problem with my phone (I read reboot should help): https://www.google.com.ua/search?q=redmi+4+stop+failed+1007+mediarecorder

**Comment by anonym24** [comment]
but https://play.google.com/store/apps/details?id=com.duapps.recorder&hl=en worls all the time 
mb they don't use mediarecorder?

**Comment by sunil-singh-chaudhary** [comment]
not working with 6.0 yes i tried it in all phone crash in mediarecorder.getsurface() Marshmallow SPICE Mi 498 phone and some other phone it is strted but notification stop button doesnt showing pls help

**Comment by vijai1996** [comment]
@sunil-singh-chaudhary Will try again on 6.0 when I'm free. 
For the stop button, you have to expand the notification using two finger swipe down.

**Comment by vijai1996** [comment]
Works perfectly on nexus 6 with 6.0. Should be an issue with the OEM. Closing this for now and will reopen when more info is given
