### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by picsi** [vijai1996/screenrecorder#3]
Hey, it would be neat to have this on the F-Droid catalog.

**Comment by vijai1996** [comment]
Let me evaluate the possibility once f-droid is up again. Seems like the site is down now

**Comment by picsi** [comment]
Seems to be working now. Here's how to: https://f-droid.org/contribute/

**Comment by vanitasvitae** [comment]
I'd really appreciate to see this app in the FDroid app store :)

**Comment by treakiandroid** [comment]
its there ive got it from there

**Comment by vijai1996** [comment]
@vanitasvitae I'd like to have a look at f-droid but its been down since yesterday night for me. And now its painfully slow
@treakiandroid can you link me please? It was definitely not put up by me

**Comment by Bugsbane** [comment]
I just installed this from droid, so it's definitely there. The bad news... it crashes instantly after clicking the confirmation screen to start recording (Samsung galaxy s5, Android 6.0. 1)

**Comment by vanitasvitae** [comment]
Ah I found it: https://f-droid.org/repository/browse/?fdfilter=screencam&fdid=com.orpheusdroid.screenrecorder

@vijai1996 I guess someone added it for you :) I hope it's not a problem for you.

**Comment by vijai1996** [comment]
@Bugsbane yeah. Its already known. CM13 and touchwiz has issues creating virtualdisplay and its causing error. I'm already into checking it but there is no time frame for the fix

@vanitasvitae yeah. F-droid added it themselves by building it from github sources and is signed by f-droid. I'm fine with anybody using the code unless they are within the license terms

**Comment by vanitasvitae** [comment]
> I'm fine with anybody using the code unless they are within the license terms

Sure they do :)
