### ISSUE TITLE
crash when editing video

### ISSUE THREAD

**Issue by pourya0111** [vijai1996/screenrecorder#32]
hey i have a problem and that is after building project when i try to edit the saved video, app crashesh on multiple devices (m above)

**Comment by vijai1996** [comment]
@pourya0111 Acknowledged. Will fix it asap. Travelling right now

**Comment by pourya0111** [comment]
i came up with new issue when selecting fps its still 30 and doesnt get my choosed number!!

**Comment by vijai1996** [comment]
Thats known and already fixed locally. Will push the commit soon

**Comment by pourya0111** [comment]
ok thanks looking forward to it

**Comment by pourya0111** [comment]
any proccess on debugging?

**Comment by vijai1996** [comment]
Well, its an incompatibility issue with the app and a library i use to edit video. The fix I made is not satisfactory to me. So I'm still exploring other options

**Comment by vijai1996** [comment]
Fixed it in [7ef08c8](https://github.com/vijai1996/screenrecorder/commit/7ef08c83317e8329a84d53bd145d0e6246b9bac9)
