### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [vijai1996/screenrecorder#33]
Hi @vijai1996 

I found [this app](https://play.google.com/store/apps/details?id=com.MediumTurquoise.screenrecorder) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU AGPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide screenshots of your own app, and a link to this repo.

**Comment by vijai1996** [comment]
Thanks for reporting it! I think I dont have to provide any screenshot as the about screen it self contains copy right notice to orpheusdroid and the libraries sections are not edited at all.

**Comment by vijai1996** [comment]
Reported the app and I will keep updating the progress here in this issue. Thanks once again for reporting it.

**Comment by Poussinou** [comment]
No problem for the screenshots, my message is a default reply I'm using to spare time when I'm hunting copies of open-source apps...

Thanks for reporting it

**Comment by vijai1996** [comment]
Haha! Yeah. I found out from the other issue in another repo I replied to. Lets hope for the best now

**Comment by vijai1996** [comment]
The app is taken down. Here is the response from Google:

> Hello,
> 
> Thanks for reaching out to us.
> 
> In accordance with the Digital Millennium Copyright Act, we have completed processing your infringement notice. We are in the process of disabling access to the content in question at the following URL(s):
> 
> https://play.google.com/store/apps/details?id=com.MediumTurquoise.screenrecorder
> 
> The content will be removed shortly.
> 
> 
> Regards,
> The Google Team

Thanks for reporting. Closing issue now.
>

**Comment by Poussinou** [comment]
Great job, thanks !
