### ISSUE TITLE
FR autoswich to a predefined app when recording.

### ISSUE THREAD

**Issue by OffifialMITX** [vijai1996/screenrecorder#34]

**Comment by vijai1996** [comment]
You mean to select a app from a list of apps and then when pressing record button, it opens the app and then starts recording?

**Comment by OffifialMITX** [comment]
Yup.

On November 27, 2017 7:27:48 AM GMT+01:00, Vijai Chander <notifications@github.com> wrote:
>You mean to select a app from a list of apps and then when pressing
>record button, it opens the app and then starts recording?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vijai1996/screenrecorder/issues/34#issuecomment-347090163

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vijai1996** [comment]
@OffifialMITX Will work on it 👍

**Comment by vijai1996** [comment]
sneak peak!
![screenshot_1512796856](https://user-images.githubusercontent.com/11158959/33792787-10a0454c-dccf-11e7-88bb-a1269d07c31f.png)

**Comment by OffifialMITX** [comment]
Yays! What's up with the status bar? Could it be a new symbol? o.0

On December 9, 2017 6:23:52 AM GMT+01:00, Vijai Chander <notifications@github.com> wrote:
>sneak peak!
>![screenshot_1512796856](https://user-images.githubusercontent.com/11158959/33792787-10a0454c-dccf-11e7-88bb-a1269d07c31f.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/vijai1996/screenrecorder/issues/34#issuecomment-350425217

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vijai1996** [comment]
That's the new android system icon from Oreo. Shown because USB debugging connected
