### ISSUE TITLE
[Bug] Unfortunately, System UI has stopped

### ISSUE THREAD

**Issue by Kristinita** [vijai1996/screenrecorder#36]
### 1. Briefly

If I record screen video use:

+ ScreenCam, I get a window `Unfortunately, System UI has stopped` and black screen,
+ another apps, I haven't bugs.

### 2. Steps to reproduce

I record my screen, see example:

+ [**ScreenCam**](https://streamable.com/8ihe2)

I can successful, without bugs, record screen video, use proprietary apps. For example, see my [**Screencast**](https://4pda.ru/forum/index.php?showtopic=446330) video:

+ [**Screencast**](https://streamable.com/jv9nd)

### 3. Hardware and software

+ ARK Benefit S401,
+ Android 5.1.1,
+ [**VERTEX**](https://4pda.ru/forum/index.php?showtopic=788444&st=80#entry56079362) ROM,
+ ScreenCam 1.8.2 (latest F-Droid version at the moment).

If I can add logs or other debugging information, please, tell me.

Thanks.

**Comment by vijai1996** [comment]
Hello, yes. Logs will help me to debug. Please add log if possible. Thanks

**Comment by Kristinita** [comment]
> Hello, yes. Logs will help me to debug. Please add log if possible. Thanks

Where is situated logs folder?

Thanks.

**Comment by Kristinita** [comment]
@vijai1996 , I can get no stack trace, use `adb`.

```bash
C:\System Volume Information>adb logcat -s com.orpheusdroid.screenrecorder
--------- beginning of system
--------- beginning of main
```

```bash
C:\System Volume Information>adb logcat -s com.android.systemui
--------- beginning of system
--------- beginning of main
```

What should I do, that add more debugging information?

Thanks.

**Comment by webhat** [comment]
I have the same issue, Trebuchet, Settings, PachageInstaller and other System tools keep crashing. Sadly I couldn't get logs as the system became too unstable.

**Comment by vijai1996** [comment]
@Kristinita sorry for the late response. Unfortunately I cannot help without any log and you can filter out the error log alone for the app using `adb logcat SCREENRECORDER_LOG:E *:S` 

@webhat That seems like a bad rom flash to me since you say many system apps are crashing. Please check your rom

**Comment by webhat** [comment]
@vijai1996 removing screencam solved it

**Comment by vijai1996** [comment]
@webhat I'm sure screencam was not the issue as it cannot cause the mentioned apps to crash

**Comment by webhat** [comment]
@vijai1996 For "fun" I installed it again, as soon as it was installed F-Droid, AFWall+, Themes Provider and Trebuchet crashed. Literally the f-droid dialog box appeared to say it was installed and the next moment I was getting: Unfortunately, <service> has stopped

I'm not so sure that it has nothing to do with it.

**Comment by vijai1996** [comment]
@webhat that only shows screencam is not the issue. Since screencam was not even running at the moment

**Comment by webhat** [comment]
@vijai1996 ok

**Comment by webhat** [comment]
You might want tot read this: https://gitlab.com/fdroid/fdroiddata/issues/979

**Comment by vijai1996** [comment]
To my understanding this seems to be fdroid/lineage bug. Can you try installing app from the github release or from play store?

**Comment by webhat** [comment]
After the reinstall to test this bug exists my phone has become to unstable, I'll be resetting and reloading the rom if I don't find a way to remove it today.

You're welcome 😎

**Comment by vijai1996** [comment]
Well, the issue on gitlab says, you can reboot to safe mode and uninstall the apps which cause the system to crash because of non-standard resource management and restart to normal mode to boot successfully. In the mean time, if you are ready to test out few test builds I'd be uploading a couple of APKs here to test.

**Comment by webhat** [comment]
Thanks, forgot about safe-mode. 😌

I don't have ga apps, but if you give me links to apks I can install them and test.

**Comment by vijai1996** [comment]
I'm attaching the test apps here. Please note that this is built from local repository and may be not stable as is. It is provided just to test if the system crash is solved.

Test this first. This is built using api27 using aapt2.
[ScreenCam api27 test build with aapt2 enabled](https://drive.google.com/file/d/1Gn03rs0e4M9dkQ20S2KPRNG4Uv1fPFyl/view?usp=sharing)

If it fails, try this. This has aapt2 disabled.
[ScreenCam api27 test build with aapt2 disabled](https://drive.google.com/file/d/1oGTkKKdHJmlWfbzj3As5roLaMsM5Cl8D/view?usp=sharing)

**Comment by webhat** [comment]
Both work without crashes

**Comment by vijai1996** [comment]
@webhat Will push the fix today then. Thanks for testing

**Comment by vijai1996** [comment]
Pushed the fix. Let's now wait for f-droid to pick the change and build the app
