### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by NitroNils** [vijai1996/screenrecorder#41]
How to stop recording when shake and onscreen controls not chosen?

**Comment by vijai1996** [comment]
@NitroNils You can stop from notification. Expand the notification using two findlger swipe gesture and press stop. Or you can also stop by going back to app and pressing the stop button

**Comment by NitroNils** [comment]
That didn't work. Oh, maybe the notification way worked, but pushing the 'stop' button gave 'Already recording' not. Will double check next time. 
-- 
Sent from my p≡p for Android.

**Comment by vijai1996** [comment]
Oops! I'm sorry it was my mistake. The 'stop' button in the app UI is removed quite a few versions before since it was causing instability. Notification action will always be there though.

Closing the issue now.
