### ISSUE TITLE
[Feature request] Immediately start recording quick settings shortcuts

### ISSUE THREAD

**Issue by mehdus** [vijai1996/screenrecorder#51]
Hello,
I think it is useful to start recording without entering the app first. Would appreciate adding a quick settings tile for that.
Home screen shortcut / app activity would be a nice addition too..
Keep up the good work!

**Comment by vijai1996** [comment]
Hi, There is already quick shortcut on compatible launchers. Just long press the app icon and you should see quick record to start recording without opening the app

**Comment by mehdus** [comment]
I didn't notice that before, any way to put it in the notification drawer?

**Comment by vijai1996** [comment]
Added in 42ed20d . Forgot to close the issue with commit
