### ISSUE TITLE
Bug on Screen Cam

### ISSUE THREAD

**Issue by iamowomizz** [vijai1996/screenrecorder#56]
**Expected Behaviour**
When ever i start a new recording then stop the recording and go to my recent apps tab on my android phone and exit the ScreenCam app, i expected the app to be taken away without crashing.

**Actual Behaviour**
When ever i start a new recording then stop the recording and go to my recent apps tab on my android phone and exit the ScreenCam app, the app crashes.

**How To Reproduce**
* download the add from fdroid
* open the app and start a new record
* got to your android notification menu to stop the app from recording
* go to your recents apps tab on your android phone to exit the app

* Browser: ScreenCam version 1.8.7

* Operating System: Android 7.0

**Recording Of The Bug**
https://youtu.be/YTD0IdsaYm8

**Comment by vijai1996** [comment]
Duplicate issue closed
