### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by amo13** [vijai1996/screenrecorder#9]
[crash.txt](https://github.com/vijai1996/screenrecorder/files/602390/crash.txt)

Hey bro, thanks a lot for this useful app, and thanks even more for having it on f-droid! Unfortunately I the app crashes very frequently on my phone. It's an Android 6.0.1. It seems to be a problem with switch to and from the app with the recent apps menu. After switching back to screenrecorder the rec button shows the stop symbol and the app crashes when I press it. I also get notified that the app crashed if I swipe it away in the recent apps menu.
I attached a log, hope it can help...

**Comment by vijai1996** [comment]
This is a known issue already and I will be soon removing the feature of stopping the recording from FAB soon in favor of floating controls (like fb messenger). It is already done and but needs optimization and refining which is taking time because of my exams. Hope to push it out soon

**Comment by amo13** [comment]
Amazing! Thanks for your work on this and good luck for your exams ;)
